arso.productos.modelo.Producto=arso.productos.repositorio.RepositorioProductoAdHocJPA
arso.productos.modelo.Categoria=arso.productos.repositorio.RepositorioCategoriaJPA
arso.productos.modelo.UsuarioResumen=arso.productos.repositorio.RepositorioUsuarioResumenJPA